# Generated by Django 3.1.2 on 2020-10-20 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
                ('seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('Event', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodCourt',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('HostelName', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceToVisit',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('PlaceName', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PresidentClub',
            fields=[
                ('presidentId', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PresidentSociety',
            fields=[
                ('presidentId', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('ShopName', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('SportName', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VicePresidentClub',
            fields=[
                ('vicepresidentId', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VicePresidentSociety',
            fields=[
                ('vicepresidentId', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('SocietyName', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
                ('President', models.ForeignKey(db_column='presidentId', on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.presidentsociety')),
                ('VicePresident', models.ForeignKey(db_column='vicepresidentId', on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.vicepresidentsociety')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False)),
                ('ClubName', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('imageUrl', models.URLField()),
                ('President', models.ForeignKey(db_column='presidentId', on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.presidentclub')),
                ('VicePresident', models.ForeignKey(db_column='vicepresidentId', on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.vicepresidentclub')),
            ],
        ),
    ]
