# Generated by Django 3.1.2 on 2020-10-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetovisit',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
